import { Logo } from '@/assets/logo'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ConvexClientProvider } from '@/providers/convex-client-provider'
import { Header } from './_components/header'

const inter = Inter({ subsets: ['latin'], variable: '--inter-font' })

export const metadata: Metadata = {
  title: 'Ignite Todo List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={`${inter.variable} font-sans`}>
        <ConvexClientProvider>
          <Header />
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  )
}
